[build]
  publish = "public"       # Yayınlanacak klasör (örnek: build, dist, public, pdfs)
  command = ""             # Derleme komutu (statik siteyse boş bırakılabilir)

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
